startups/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from usercp import views
from .api import shetabs_json, startups_api

urlpatterns = [
     path('', views.redirect_url_to_register, name='redirect_url'),
     path('admin/', admin.site.urls),
     path('admin/doc/', include('django.contrib.admindocs.urls')),
     path('', include(('usercp.urls', 'usercp'), namespace='usercp')),
     path('', include(('startup.urls', 'startup'), namespace='startup')),
     path('', include(('theevent.urls', 'theevent'), namespace='theevent')),
     path('', include(('category.urls', 'category'), namespace='category')),
     path('', include(('usertracker.urls', 'usertracker'), namespace='usertracker')),
     path('', include(('message.urls', 'message'), namespace='message')),

     path('api/', shetabs_json, name='shetabs_json'),
     path('api/startup/', startups_api, name='shetabs_json'),
     path('logs/all', views.all_logs, name='my_logs'),
     path('logs/urls', views.url_logs, name='url_logs'),
]

handler404 = views.my_404_error
handler500 = views.my_500_error

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usercp/urls.py
from django.conf.urls import url
from django.urls import path, include
from usercp import views
from django.contrib.auth.views import LoginView, PasswordResetView

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('dashboard/', views.dashboard_panel, name='dashboard_panel'),
    path('mentors/', views.profile_mentor, name='profile_mentor'),
    path('sort-mentors/', views.sort_mentors, name='sort_mentors'),
    path('add-to-mentor/', views.add_to_mentor, name='add_to_mentor'),
    path('verify/', views.verify_user, name='verify'),
    path('send-sms/verify', views.send_sms_again, name='send_sms_again'),
    path('startup/', views.startup, name='startup'),
    path('team/', views.team, name='team'),
    path('upload/', views.upload, name='upload'),
    path('uploadv/', views.upload_video_action, name='upload_video'),
    path('presentation/', views.presentation, name='presentation'),
    path('upload-pdf/<int:startup_id>/', views.pgdeck, name='pgdeck_pdf'),
    path('upload-xwlt/<int:startup_id>/', views.pgdeckxwlt, name='pgdeckxwlt'),
    path('finish/', views.finish, name='finish'),
    path('profiles/<int:user_id>/', views.profiles, name='profiles'),
    path('remove-team-member/', views.remove_team_member, name='remove_team_member'),
    # path('remove-video/', views.remove_video, name='remove_video'),
    # path('remove-from-mentor/', views.remove_from_mentor,
    #      name='remove_from_mentor'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('ghost/<int:user_id>/', views.ghost_mode, name='ghost_mode'),
    path('ghost-out/', views.ghost_mode_out, name='ghost_mode_out'),
    path('list-user/', views.list_user, name='list_user'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('create-user/', views.create_user, name='create_user'),
    path('login/', views.login_view, name='login'),
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('forget-password/', views.forget_password, name='forget_password'),
    path('change-username/', views.change_username, name='change_username'),
    path('change-password/', views.change_password, name='change_password'),
    url(r'^new-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.new_password, name='new_password'),
]

usercp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from category.models import Categories

# Create your models here.


class Role(models.Model):
    """the roles that will assign to karmand users
    
    Arguments:
        models {MODEL} -- built-in django model
    
    Returns:
        STRING -- returns the persian side of each role
    """
    THE_ROLES = (
        ('financial', 'مالی'),
        ('coach', 'مربی'),
        ('leader', 'راهبر'),
        ('surpreme', 'راهبر ارشد'),
        ('investor', 'سرمایه گذار'),
        ('referee', 'داور'),
        ('operational', 'مدیر عملیات'),
    )
    name = models.CharField(max_length=11, choices=THE_ROLES)

    def __str__(self):
        return self.get_name_display()


class UserManager(BaseUserManager):
    """to create some custom manager (ORM)
    
    Arguments:
        BaseUserManager {CLASS} -- a django built-in class
    
    Raises:
        ValueError: ensure that the user must have a phone number
        ValueError: ensure that the user must have an email
    
    Returns:
        OBJECT -- created record of user
    """

    def create_startup_user(self, phone, password=None, username=None):
        """custom ORM to create an account for owner of startup
        
        Arguments:
            phone {STRING} -- startups owner phone number
        
        Keyword Arguments:
            password {STRING} -- a random password (default: {None})
            username {STRING} -- a random username (default: {None})
        
        Raises:
            ValueError: raise an error if user do not enter any phone number
        
        Returns:
            OBJECT -- returns created user
        """
        user = self.model(phone=phone)
        if not phone:
            raise ValueError('User must have phone')

        user.step = 'startup'
        user.username = username
        user.set_password(password)
        user.user_type = 'startup'
        user.save(using=self._db)

        return user


    def create_user(self, email, phone, password=None, **kwargs):
        """create and save a new user
        
        Arguments:
            email {STRING} -- an email value
            phone {STRING} -- a phone value
        
        Keyword Arguments:
            password {STRING} -- a password (default: {None})
        
        Raises:
            ValueError: raise an error if user don't enter an email
        
        Returns:
            OBJECT -- reutrns created user
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email), phone=phone, **kwargs)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, phone, password=None):
        """Creates and saves a superuser with the given email, phone and password.
        
        Arguments:
            email {STRING} -- an email value
            phone {STRING} -- a phone value
        
        Keyword Arguments:
            password {STRING} -- a password (default: {None})
        
        Returns:
            OBJECT -- returns created user
        """
        user = self.create_user(
            email=email,
            phone=phone,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """a custome user model that use phone number to login
    
    Arguments:
        AbstractBaseUser {CLASS} -- a django built-in class
    
    Returns:
        STRING -- returns user first_name last_name or phone number
    """

    id = models.AutoField(primary_key=True, editable=False, unique=True)

    username = models.CharField(
        max_length=150, unique=True, blank=True, null=True)
    first_name = models.CharField(max_length=120, blank=True)
    last_name = models.CharField(max_length=120, blank=True)
    email = models.EmailField(
        max_length=255, unique=False)
    phone_reg = RegexValidator(regex=r'[0][9][0-9]{9,9}$')
    phone = models.CharField(
        validators=[phone_reg],
        max_length=120,
        unique=True
    )
    avatar = models.ImageField(blank=True, null=True, upload_to='user/avatar/%Y-%m-%d')
    USER_TYPES = (
        ('startup', 'استارت اپ'),
        ('shetab', 'شتاب دهنده'),
        ('manager', 'مدیر'),
        ('karmand', 'کارمند'),
    )
    user_type = models.CharField(max_length=10, choices=USER_TYPES, blank=True)
    user_type2 = models.CharField(
        max_length=10, choices=USER_TYPES, blank=True)
    STARTUP_STEPS = (
        ('register', 'آغاز ثبت نام'),
        ('verify', 'اعتبار سنجی'),
        ('startup', 'معرفی استارت اپ'),
        ('team', 'اطلاعات تیم'),
        ('upload', 'معرفی ویدئو'),
        ('presentation', 'پیج دک'),
        ('finish', 'تایید نهایی'),
    )
    step = models.CharField(
        max_length=15, choices=STARTUP_STEPS, default='register')

    role = models.ManyToManyField(
        Role, related_name='user', blank=True)
    category = models.ManyToManyField(
        Categories, related_name='user', blank=True)
    linkdin = models.CharField(max_length=120, blank=True, null=True)
    twitter = models.CharField(max_length=120, blank=True, null=True)
    instagram = models.CharField(max_length=120, blank=True, null=True)
    city = models.CharField(max_length=120, blank=True, null=True)
    site = models.URLField(max_length=120, blank=True, null=True)
    bio = models.TextField(max_length=255, blank=True, null=True)
    birth_date = models.DateField(max_length=100, blank=True, null=True)
    skill = models.CharField(max_length=200, blank=True, null=True)
    STUDIED = (
        ('diploma', 'دیپلم'),
        ('associate', 'کاردانی'),
        ('bachelor', 'کارشناسی'),
        ('master', 'کارشناسی ارشد'),
        ('phd', 'دکتری'),

    )
    grade = models.CharField(max_length=70, blank=True,
                             null=True, choices=STUDIED)
    multi = models.PositiveIntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    # is_passed = models.BooleanField(default=True)
    add_to_mentors = models.BooleanField(default=False)
    mentor_user = models.BooleanField(default=False)
    sort = models.IntegerField(blank=True, null=True)
    is_compeleted = models.BooleanField(default=False)
    can_see = models.BooleanField(default=False)
    can_see_startups = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['email']

    def __str__(self):

        return f'{self.first_name} { self.last_name }' if self.first_name != '' or self.last_name != '' else f'{self.phone}'

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

usercp/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, SetPasswordForm
from django.contrib.auth import authenticate
from .models import User, Role
from startup.models import UserProfile


class UserStartupRegisterForm(forms.ModelForm):
    """a custom form for admin.py
    
    Arguments:
        forms {MODULE} -- a django built-in ModelForm
    
    Raises:
        forms.ValidationError: raise an error if passowrds don't match
    
    Returns:
        OBJECT -- returns created user
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        models = User
        fields = ('phone', 'email',)

    def clean_password2(self):
        """check if the passwords match
        
        Raises:
            forms.ValidationError: raise an error if passwords are not match
        
        Returns:
            STRING -- returns password2
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        """set user passowrd before saving to database
        
        Keyword Arguments:
            commit {BOOLEAN} -- to stop commit when setting password (default: {True})
        
        Returns:
            OBJECT -- returns created user
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'phone', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]




class UserProfileForm(forms.ModelForm):
    """a form for startups owner to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        models = UserProfile
        exclude = ('user',)



class UserRegisterForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('phone',)


class UserCreateRole(forms.ModelForm):
    """a form to create karmand type user
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'email')


class LeaderForm(forms.ModelForm):
    """a form for startups owner to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = UserProfile
        fields = ('saham', 'duration_per_month')


class LeaderUserForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('phone', 'first_name', 'last_name',
                  'email', 'linkdin', 'grade', 'skill')



class KarmandForm(forms.ModelForm):
    """a form to create karmand type user
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'phone', 'email', 'linkdin', 'multi', 'avatar', 'can_see_startups')


class ProfileAdminForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('email', 'linkdin', 'skill', 'grade')


class ProfileRoleForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('email', 'linkdin', 'twitter', 'site',
                  'city', 'instagram', 'bio', 'skill', 'grade')


class PasswordChangeForm(SetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = {
        **SetPasswordForm.error_messages,
    }

    field_order = ['new_password1', 'new_password2']





class LoginForm(forms.Form):
    """a custom form for login
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    username = forms.CharField(max_length=120)
    password = forms.CharField(
        max_length=120, widget=forms.PasswordInput)

usercp/templates/usercp/panel/forget-password.html
{% extends 'base/base-public.html' %}
{% load static %}
{% block title %}فراموشی رمز عبور{% endblock %}
{% block body %}
        <!-- <div class="colm8 colm margin-auto alert-sucsess bg-white flex-center color-black font-w400 font-s15 border-ra5 a pad-20 wow fadeInDown"  data-wow-duration="1.5s">
            <h2 class="flex-center-row"><i class="fa fa-times pad-l5"></i>شماره موبایل وارد شده یافت نشد</h2>
		</div> -->
<style>
			.chenge-pass {
				position: fixed;
				left: 2%;
				border: 1px solid #2222222e;
				bottom: 5%;
				box-shadow: 7px 10px 0px 2px #ffffff;
			}
</style>
<div id="login-panel" class="container-fluide  min-100vh">
	<div class="flex-center min-h100">
		<div class="colm4-login colm10-mob colm6-tab colm">
			 <div class="pad-b20">
			</div>
			<div class="spacer-t25">
				<form action="" method="post" class="smart-validate">{% csrf_token %}
                    <div class="">
						<div class="body-form relative">
							<div class=" body-form-top margin-auto absolute pad-b30">
								<div class="img-login margin-auto">
										<img src="{% static 'images/logo-panel.svg' %}" />
								</div>
							</div>
							<div class="pad-t100">
						    	<div class="colm10 colm margin-auto font-s14 spacer-t10">
                                    <div class="font-s12 pad-15">لطفا نام کاربری یا ایمیل خود را جهت ارسال لینک تایید وارد نمایید</div>
								     <input class="input-panel" id="mobile" name="mobile" required>
								     <span class="bar"></span>
								     <label for="mobile" class="label font-s12 spacer-t10">نام کاربری / ایمیل</label>
							    </div>
							</div>
							{% for message in messages %}
								
							{% if 'no_user_email_forget' in message.extra_tags %}
							<div class="colm colm10 margin-auto">
								<h2 class="color-red error-user  font-s12">چنین ایمیل یا نام کاربری موجود نیست</h2>
							</div>
							{% endif %}
							{% if 'forget_password_compeleted' in message.extra_tags %}
							<div class="colm colm10 margin-auto">
								<h2 class="color-green error-user  font-s12">لینک فراموشی رمز عبور برای ایمیل شما ارسال شد</h2>
							</div>
							{% endif %}

							{% endfor %}
							<div class="margin-auto align-center pad-b25">
								<button type="submit" name="submit" class="btn-panel pad-10 color-white iransans">تغیر رمز عبور</button>
							</div>
						</div>
                    </div>
				</form>
			</div>
			<div class="pad-t10">
				<a href="{% url 'usercp:login' %}" class="title color-white">
					<i class="fa fa-home vertical pad-r5"></i>
					<span>ورود به پنل</span>
				</a>
			</div>


		</div>
	</div>
						{% for message in messages %}

		{% if 'email_sent_for_user' in message.extra_tags %}
		<div class="alert-sucsess bg-white flex-center colm3 colm color-black font-w400 font-s13 border-ra5 a pad-20 chenge-pass le">
			<h2 class="flex-center-row"><i class="fa fa-times pad-l5"></i>لینک تایید به ایمیل شما ارسال شد</h2>
		</div>
        {% comment %} <div class="colm8 colm margin-auto alert-sucsess bg-white flex-center color-black font-w400 font-s15 border-ra5 a pad-20 wow fadeInDown"  data-wow-duration="1.5s">
            <h2 class="flex-center-row"><i class="fa fa-times pad-l5"></i>لینک تایید به ایمیل شما ارسال شد</h2>
		</div> {% endcomment %}
		{% endif %}
		{% endfor %}
	<div class="clearfix"></div>

</div>
<style>
	header , footer{
		display: none;
	}
</style>
{% endblock %}
{% block script %}
  <script>
      jQuery(document).ready(function($){
          window.setTimeout(function() {
              $(".alert-sucsess").fadeTo(500, 0).slideUp(500, function(){
                  $(this).remove();
              });
          }, 4000);
      })
  </script>
{% endblock %}

usercp/templates/usercp/panel/new-password.html
{% extends 'base/base-public.html' %}
{% load static %}
{% block title %}پسورد جدید{% endblock %}
{% block body %}
<div id="login-panel" class="container-fluide  min-100vh">
	<div class="flex-center min-h100">
		<div class="colm4-login colm10-mob colm6-tab colm">
			 <div class="pad-b20">
			</div>
			<div class="spacer-t25">
				<form action="" method="post" class="smart-validate">{% csrf_token %}
                    <div class="">
						<div class="body-form relative">
							<div class=" body-form-top margin-auto absolute pad-b30">
								<div class="img-login margin-auto">
                    <img src="{% static 'images/logo-panel.svg' %}" />
								</div>
							</div>
							<div class="pad-t100">
						    	<div class="colm10 colm margin-auto font-s14 spacer-t10">
                                    <div class="font-s12 pad-15">لطفا رمز عبور جدید خود را وارد نمایید</div>
                                     <input class="input-panel" dir="ltr"  id="password-field" type="password" name="new_password" required>
                                     <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password color-icon pull-left pad-t5"></span>
								     <span class="bar"></span>
								     <label for="mobile" class="label font-s12 spacer-t10">رمز عبور جدید</label>
							    </div>
							</div>
							{% for message in messages %}

							{% if 'password_not_changed' in message.extra_tags %}
							<div class="colm8 colm margin-auto alert-sucsess bg-white flex-center color-black font-w400 font-s15 border-ra5 a pad-20 wow fadeInDown"
								data-wow-duration="1.5s">
								<h2 class="flex-center-row"><i class="fa fa-check pad-l5"></i>لطفا دوباره تلاش کنید</h2>
							</div>
							{% endif %}
							{% endfor %}
							<div class="margin-auto align-center pad-b25">
								<button type="submit" name="submit" class="btn-panel pad-10 color-white iransans">تغیر رمز عبور</button>
							</div>
						</div>
                    </div>
				</form>
			</div>
			<div class="pad-t10">
				<a href="{% url 'usercp:login' %}" class="title color-white">
					<i class="fa fa-home vertical pad-r5"></i>
					<span>ورود به پنل</span>
				</a>
			</div>
		</div>
	</div>
	<div class="clearfix"></div>
</div>
<style>
	header , footer{
		display: none;
	}
</style>
{% endblock %}
{% block script %}
<script>
    jQuery(document).ready(function($) {
        $(".toggle-password").click(function() {
            $(this).toggleClass("fa-eye fa-eye-slash");
            var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
            input.attr("type", "text");
            } else {
            input.attr("type", "password");
            }
        });

    });
</script>
{% endblock %}

usercp/templates/usercp/panel/profile-mentor.html
{% extends 'base/base-public.html' %}
{% load static %}
{% block title %}منتور ها{% endblock %}
{% block body %}
<style>
	footer {
		display: none
	}
	.scroll-cat{
		height: 46px;
    	overflow: hidden;
	}
	.input-mentor {
		width: 100%;
		color: #747474;
		font-size: 13px;
		background: transparent;
		border: 1px solid #666666;
		padding: 8px 52px 8px 20px;
		border-radius: 24px;
		-webkit-appearance: none; 
		transition: all .2s ease-out;
	}

	.border-none {
		border: none;	new WOW().init();

	}

	.p-mentors {
		border-radius: 100%;
		overflow: hidden;
		cursor: pointer;
		margin: 0 auto;
	}

	.box-mentors {
		border: 2px dashed #fff;
		border-radius: 10px;
		outline: none;
	}

	.box-mentors {
		border: 2px dashed #fff;
		border-radius: 10px;
		outline: none;
	}

	.h200 {
		height: 200px;
	}

	.back-border {
		background: linear-gradient(45deg, #69c565db, #12c2d64f);
		border-bottom: 2px solid #00a1bc;
	}

	.color-search {
		color: #027386;
	}
</style>
<header id="header" class="container-fluid hide-tab hidden-xs">
	<div class="container">
		<div class="header-logo pull-right pad-t10 pad-l40">
			<a href="https://100startups.ir">
				<span>صـــداستــارت آپ</span>
			</a>
		</div>
		<div class="header-menu pull-right">
			<nav class="main-menu">
				<ul id="menu-main-menu" class="menu">
					<li id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home menu-item-249"><a href="{% url 'usercp:register' %}">ثبت نام</a></li>
					<!-- <li id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-250"><a href="">ورود به پنل</a></li> -->
				</ul>
			</nav>
		</div>
		{% if request.user.is_authenticated %}
		<div class="header-signup pull-left pad-10"> <a href="{% url 'usercp:logout' %}"> <span class="font-s14 color-white">خروج</span> </a> </div>
		{% else %}
		<div class="header-signup pull-left pad-10"> <a href="{% url 'usercp:login' %}"> <span class="font-s14 color-white">ورود</span> </a> </div>
		{% endif %}
		<div class="clearfix"></div>
	</div>
</header>
<div id="section-step" class="container-fluide  min-100vh flex-center">
	<div class="container pad-20 pad-step pad-50-tmob">
		<div class="body-form spacer-t50">
			<div class="back-border">
				<h2 class="font-s22 color-blue pad-10  pull-right"><i class="fa fa-chalkboard-teacher vertical pad-l5"></i> راهبران/مربیان صد استارتاپ</h2>
				<h2 class="font-s22 color-search pad-10 pull-left"><i class="fa fa-search vertical pad-l5 search-mentor"></i></h2>
				<div class="colm6 colm pull-left filter-m hide">
					<form method="get" action="">
						<div class="relative colm4 colm pull-right pad-5 pad-b20">
							<label for="lname-search" class="gui-label">نام نام خانوادگی:</label>
							<label class="relative">
								<span class="icon-gui flex-center"><i class=" fa fa-user vertical"></i></span>
								<input type="search" value="" name="full_search" id="fname-search" class="input-mentor gui-input">
							</label>
						</div>
						<div class="relative colm4 colm pull-right pad-5 pad-b20">
							<label for="roles-search" class="gui-label">حوزه فعالیت:</label>
							<label class="relative pad-b20">
								<span class="icon-gui flex-center"><i class=" fa fa-user vertical"></i></span>
								<select class="input-mentor gui-input" name="cats">
									<option value="">انتخاب کنید</option>
									{% for cat in categories %}
									<option value="{{cat.id}}">{{cat.title}}</option>
									{% endfor %}
								</select>
							</label>
						</div>
						<div class="pull-right align-center pad-t30">
							<button name="submit_search" type="submit" class="btn-prv pointer">جستجو</button>
						</div>
						<div class="clearfix"></div>
					</form>
				</div>
				<div class="clearfix"></div>
			</div>
{% for profile in the_mentors %}
					<div class="colm3 colm pull-right pad-10">
						<div class="">
							<div class="border-none pad-20 h200 flex-center">
								<img width="150" alt="logo" class="p-mentors" src="{% if profile.avatar %}{{profile.avatar.url}}{% else %}{% static "images/avatar1.png"%}{% endif%}" />
							</div>
							<p class="align-center color-blue font-s20 pad-b10">{% if profile.last_name and profile.first_name %}{{ profile.first_name }} {{ profile.last_name }}{%else%}{{ profile.username}}{% endif %}</p>
							<p class="align-center color-dashboard font-s15 pad-b10 scroll-cat">{% for cat in profile.category.all %}{{cat.title}}{% if not forloop.last%} ، {% endif %}{% empty %}حوزه فعایت وارد نشده{% endfor %}</p>
						</div>
					</div>
					{% endfor %}
			<div class="clearfix"></div>
		</div>
	</div>
</div>
{% endblock %}
{% block script %}
<script>
	jQuery(document).ready(function($) {
		$('.search-mentor').click(function() {
			$('.filter-m').toggle('3000');
		});
	});
</script>
{% endblock %}