category/urls.py
from django.urls import path, include
from category import views

urlpatterns = [
    
     path('list-cat/', views.list_cat, name='list_cat'),
     path('can-see-cat/', views.can_see_cat, name='can_see_cat'),
     path('edit-cat/<int:categories_id>/<slug>/', views.edit_cat, name='edit_cat'),
     path('delete-cat/', views.delete_cat, name='delete_cat'),
     path('create-cat/', views.create_cat, name='create_cat'),
]

startups/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from usercp import views
from .api import shetabs_json, startups_api

urlpatterns = [
     path('', views.redirect_url_to_register, name='redirect_url'),
     path('admin/', admin.site.urls),
     path('admin/doc/', include('django.contrib.admindocs.urls')),
     path('', include(('usercp.urls', 'usercp'), namespace='usercp')),
     path('', include(('startup.urls', 'startup'), namespace='startup')),
     path('', include(('theevent.urls', 'theevent'), namespace='theevent')),
     path('', include(('category.urls', 'category'), namespace='category')),
     path('', include(('usertracker.urls', 'usertracker'), namespace='usertracker')),
     path('', include(('message.urls', 'message'), namespace='message')),

     path('api/', shetabs_json, name='shetabs_json'),
     path('api/startup/', startups_api, name='shetabs_json'),
     path('logs/all', views.all_logs, name='my_logs'),
     path('logs/urls', views.url_logs, name='url_logs'),
]

handler404 = views.my_404_error
handler500 = views.my_500_error

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usercp/urls.py
from django.conf.urls import url
from django.urls import path, include
from usercp import views
from django.contrib.auth.views import LoginView, PasswordResetView

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('dashboard/', views.dashboard_panel, name='dashboard_panel'),
    path('mentors/', views.profile_mentor, name='profile_mentor'),
    path('sort-mentors/', views.sort_mentors, name='sort_mentors'),
    path('add-to-mentor/', views.add_to_mentor, name='add_to_mentor'),
    path('verify/', views.verify_user, name='verify'),
    path('send-sms/verify', views.send_sms_again, name='send_sms_again'),
    path('startup/', views.startup, name='startup'),
    path('team/', views.team, name='team'),
    path('upload/', views.upload, name='upload'),
    path('uploadv/', views.upload_video_action, name='upload_video'),
    path('presentation/', views.presentation, name='presentation'),
    path('upload-pdf/<int:startup_id>/', views.pgdeck, name='pgdeck_pdf'),
    path('upload-xwlt/<int:startup_id>/', views.pgdeckxwlt, name='pgdeckxwlt'),
    path('finish/', views.finish, name='finish'),
    path('profiles/<int:user_id>/', views.profiles, name='profiles'),
    path('remove-team-member/', views.remove_team_member, name='remove_team_member'),
    # path('remove-video/', views.remove_video, name='remove_video'),
    # path('remove-from-mentor/', views.remove_from_mentor,
    #      name='remove_from_mentor'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('ghost/<int:user_id>/', views.ghost_mode, name='ghost_mode'),
    path('ghost-out/', views.ghost_mode_out, name='ghost_mode_out'),
    path('list-user/', views.list_user, name='list_user'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('create-user/', views.create_user, name='create_user'),
    path('login/', views.login_view, name='login'),
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('forget-password/', views.forget_password, name='forget_password'),
    path('change-username/', views.change_username, name='change_username'),
    path('change-password/', views.change_password, name='change_password'),
    url(r'^new-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.new_password, name='new_password'),
]

category/models.py
from django.db import models

# Create your models here.


class Categories(models.Model):
    """a table to stor category with title, style, image and description
       and is_available field for show or not show category at registartion process

    Arguments:
        models {MODULE} -- a django built-in class to define tables

    Returns:
        STRING -- returns title of category
    """    
    id = models.AutoField(primary_key=True, unique=True)
    title = models.CharField(max_length=120, blank=True)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField(max_length=225, blank=True, null=True)
    image = models.ImageField(blank=True, upload_to='category/img/%Y-%m-%d')

    is_available = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

category/forms.py
from django import forms
from category.models import Categories

class CategoryForm(forms.ModelForm):
    """a model form for Categoires model with all fields

    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """    
    class Meta:
        model = Categories
        fields = '__all__'

category/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core import files
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from . import models
from usertracker.models import UserTracker
from django.core.paginator import Paginator
from .forms import CategoryForm

from django.contrib.auth.decorators import login_required
from startups.utils import get_client_ip, premession, logging_view, status_of_user, resize_pics
from .services import *
import re
import logging

logger = logging.getLogger(__name__)

# Create your views here.


@logging_view
@login_required(login_url='usercp:login')
@premession(th_type1='manager',  role=['operational', ])
# @user_tracker()
def list_cat(request):
    """list of categories with pagination

    Arguments:
        request {REQUEST} -- to get page number and track user

    Returns:
        RENDER -- renders the list-cat html file
    """    
    offset = request.GET.get('page')
    return render(request, 'category/list-cat.html', list_category_service(request.track_info, offset))


@logging_view
@login_required(login_url='usercp:login')
# @user_tracker()
def delete_cat(request):
    """allow user to delete specific category which id of it will given by ajax

    Arguments:
        request {REQUEST} -- to check if the reqeust is ajax

    Returns:
        JSONRESPONSE -- returns back the id of the category to ajax
    """    
    if request.is_ajax():
        cat_id = request.POST.get('delete_cat_id')
        return JsonResponse(delete_category_service(cat_id, request.track_info))
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@logging_view
@login_required(login_url='usercp:login')
@premession(th_type1='manager',  role=['operational', ])
# @user_tracker(model='categories')
def create_cat(request):
    """allow users with role of admin or manager or operational to create a new category

    Arguments:
        request {REQEUST} -- to define method of form and get image

    Returns:
        RENDRES -- renders the create-cat html file
    """    
    if request.method == "POST":
        file_value = request.FILES
        form = request.POST
        cat_form = create_category_service(form, file_value, request.track_info)
        if cat_form == True:
            return redirect('category:list_cat')
        else:
            messages.warning(request, str(cat_form),
                             extra_tags='category_error')

    return render(request, 'category/create-cat.html')


@logging_view
@login_required(login_url='usercp:login')
@premession(th_type1='manager',  role=['operational', ])
# @user_tracker(model='categories')
def edit_cat(request, categories_id, slug):
    """allow users with role of admin or manager or operational to edit specific category

    Arguments:
        request {REQUEST} -- to 
        id {INT} -- the id of selected category
        slug {SLUG} -- the slug of selected category

    Returns:
        RENDRES -- renders the edit-cat html file
    """    
    cat_form, category =  edit_category_instance_service(categories_id, slug)
    if request.method == "POST":
        file_value = request.FILES
        form = request.POST
        cat_form = edit_category_service(form, file_value, request.track_info, category)
        if cat_form == True:
            return redirect('category:list_cat')
        else:
            messages.warning(request, str(cat_form),
                             extra_tags='edit_cat_form_error')
    return render(request, 'category/edit-cat.html', {"cat_form": cat_form,"category": category})


@logging_view
@login_required(login_url='usercp:login')
# @user_tracker()
def can_see_cat(request):
    """give selection access to category on registeration process or vice versa

    Arguments:
        request {REQUEST} -- to check if the request is ajax or not

    Returns:
        JSONRESPONSE -- returns back the id of the category to ajax
    """    
    if request.is_ajax():
        cat_id = request.POST.get('add_id')
        return JsonResponse(can_see_category_service(cat_id))
    return HttpResponseRedirect(request.META.get("HTTP_REFEREE"))

category/templates/category/create-cat.html
{% extends 'base/base-panel.html' %}
{% load static %}
{% block title %}ساخت حوزه فعالیت{% endblock %}
{% block body %}
<style>


    .pre-logo {
        width:  200px;
        height: 200px;
        margin-right: auto;
        margin-left: auto;
        border-radius: 50%;
        border: 2px double #ebebeb;
        padding: 6px;
    }

    .blue-btn:hover,
    .blue-btn:active,
    .blue-btn:focus,
    .blue-btn {
        background: transparent;
        border: solid 1px #27a9e0;
        border-radius: 20px;
        color: #27a9e0;
        font-size: 16px;
        text-align: center;
        margin-bottom: 20px;
        outline: none !important;
        padding: 6px 20px;
    }

    .fileUpload {
        position: relative;
        overflow: hidden;
        height: 43px;
        margin-top: 30px;
    }

    .fileUpload input.uploadlogo {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        padding: 0;
        font-size: 20px;
        text-align: center;
        cursor: pointer;
        opacity: 0;
        filter: alpha(opacity=0);
        width: 100%;
        height: 42px;
    }

    /*Chrome fix*/
    input::-webkit-file-upload-button {
        cursor: pointer !important;
        height: 42px;
        width: 100%;
    }
</style>
{% for message in messages %}
    {% if 'category_error' in message.extra_tags %}
    <div class="colm8 colm margin-auto alert-sucsess bg-white flex-center color-black font-w400 font-s15 border-ra5 a pad-20 wow fadeInDown"
        data-wow-duration="1.5s">
        <h2 class="flex-center-row"><i class="fa fa-times pad-l5"></i>{{ message.tags }}</h2>
    </div>
    {% endif %}
    {% endfor %}
    <div class="colm8 colm12-tab colm margin-auto spacer-t30">
        <form action="" method="post" class="smart-validate" enctype="multipart/form-data">{% csrf_token %}
            <!-- {{ cat_form }} -->
            <div class="body-form relative">
                <div class="bg-chart4 body-form-top absolute flex-center">
                    <div class="fa fa-file vertical font-s30 color-white"></div>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18 pad-r25">ایجاد دسته بندی</h3>
                </div>
                <div class="pad-30">
                    <div class="frm-row spacer-t30">
                        <div class="colm5 colm pull-right pad-5">
                            <label for="cat-title" class="gui-label pad-5">نام دسته بندی :</label>
                            <label class="relative">
                                <span class="icon-gui flex-center"><i class=" fa fa-folder-plus vertical"></i></span>
                                <input type="text" class="gui-input sans-digit" id="cat-title" name="title" required>
                            </label>
                        </div>
                        <div class="colm4 colm pull-right pad-5">
                            <label for="cat-slug" class="gui-label pad-5">نامک :</label>
                            <label class="relative">
                                <span class="icon-gui flex-center"><i class=" fa fa-font vertical"></i></span>
                                <input type="text" class="gui-input sans-digit" id="cat-slug" name="slug" data-rule-lettersonlyen="true" required>
                            </label>
                        </div>
                        <div class="colm3 colm pull-right pad-5">
                            <div>
                                <div class="fileUpload blue-btn btn width100">
                                    <i class="fa fa-plus pad-5 font-s15"></i>
                                    <span class="pad-t5 font-s15">لوگو</span>
                                    <input type="file" name="image" class="uploadlogo" id="imgInp" accept="image/*" onchange="loadFile(event)" required>
                                </div>
                            </div>
                        </div>
                        <div class="colm12 colm pull-right pad-5">
                            <label for="cat_expressions" class="gui-label pad-5">توضیحات :</label>
                            <label class="relative">
                                <textarea cols="70" rows="3" class="gui-input sans-digit" id="cat_expressions" name="description" data-rule-lettersonly="true"></textarea>
                            </label>
                        </div>
                        <div class="colm12 colm">
                            <img id="output" class="pre-logo hide">
                        </div>

                    </div>
                    <div class="margin-auto align-center pad-t10">
                        <button type="submit" name="submit" class="btn-panel pad-10 color-white iransans">افزودن</button>
                    </div>
                </div>
        </form>

    </div>


{% endblock %}
{% block script %}
<script>
    jQuery(document).ready(function($) {
        $('.uploadlogo').change(function() {
            $('.pre-logo').removeClass('hide').addClass('show');
        })
    })
    

    var loadFile = function(event) {
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
    };

</script>
{% endblock %}

category/templates/category/list-cat.html
{% extends 'base/base-panel.html' %}
{% load static %}
{% block title %}لیست حوزه فعالیت{% endblock %}
{% block body %}
<style>
    .bg-red {
    background: #cc4646;
}
</style>
    <div class="colm9 margin-auto colm12-tab colm12-tab colm pad-15 pad-t40 pad-5-mob wow slideInRight" data-wow-duration="1.5s">
        <div class="body-form relative pad-b10">
            <div class="payam">
                <div class="bg-red body-form-top absolute flex-center">
                    <i class="fa fa-bell vertical font-s30 color-white"></i>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18">دسته ها</h3>
                </div>
            </div>
            <div class="pad-table">
                <div class="frm-row pad-t40">
                    <div class="overflow-scroll pad-b40">
                        <table class="table color6 retable">
                            <thead>
                            <tr>
                                <th>ردیف</th>
                                <th>عنوان دسته</th>
                                <th>ویرایش</th>
                                <th>حذف</th>
                                <th class="center">نمایش به تیم ها</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for cat in categories %}
                                <tr id="{{ cat.pk }}">
                                    <td>{{ forloop.counter0|add:categories.start_index }}</td>
                                    <td>{{ cat.title }}</td>
                                    <td>
                                        <a class="color-silver" title="ویرایش" href="{% url 'category:edit_cat' cat.pk cat.slug %}">
                                            <i class="font-s20 fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <span class="color-silver cat-delete pointer" title="حذف" data-cat="{{ cat.pk }}" data-name="{{ cat.title }}">
                                            <i class="font-s20 fa fa-trash"></i>
                                        </span>
                                    </td>
                                    <td class="center">
                                        <span class="add-look color-silver  pointer flex-center" title="اضافه شده" data-name="{{ cat.title }}" data-add="{{cat.pk}}">
                                            <i class="font-s25 fa {% if cat.is_available %}fa-check color-green{%else%} fa-plus color-blue{% endif %}"></i>
                                        </span>
                                    </td>
                                </tr>
{% endfor %}
                            </tbody>
                        </table>
                        <div class="paging">
                            {% if categories.has_other_pages %}
                            <div class="pagination">
                                <br>
                                {% if categories.has_previous %}
                                <a class="" href="?page=1">«</a>
                                <a class="" href="?page={{ categories.previous_page_number }}">‹</a>
                                {% endif %}
                        
                                {% for num in categories.paginator.page_range %}
                                {% if categories.number == num %}
                                <span class="current">{{ num }}</span>
                                {% elif num > categories.number|add:'-3' and num < categories.number|add:'3' %}
                                <a class="" href="?page={{ num }}">{{ num }}</a>
                                {% endif %}
                                {% endfor %}
                        
                                {% if categories.has_next %}
                                <a class="btn btn-outline-warning mb-4" href="?page={{ categories.next_page_number }}">›</a>
                                <a class="btn btn-outline-warning mb-4" href="?page={{ categories.paginator.num_pages }}">»</a>
                                {% endif %}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- modal -->
{% for cat in categories %}
    <div class="modal-overlay">
        <div class="modal">

            <a class="close-modal">
                <svg viewBox="0 0 20 20">
                    <path fill="#000000" d="M15.898,4.045c-0.271-0.272-0.713-0.272-0.986,0l-4.71,4.711L5.493,4.045c-0.272-0.272-0.714-0.272-0.986,0s-0.272,0.714,0,0.986l4.709,4.711l-4.71,4.711c-0.272,0.271-0.272,0.713,0,0.986c0.136,0.136,0.314,0.203,0.492,0.203c0.179,0,0.357-0.067,0.493-0.203l4.711-4.711l4.71,4.711c0.137,0.136,0.314,0.203,0.494,0.203c0.178,0,0.355-0.067,0.492-0.203c0.273-0.273,0.273-0.715,0-0.986l-4.711-4.711l4.711-4.711C16.172,4.759,16.172,4.317,15.898,4.045z"></path>
                </svg>
            </a><!-- close modal -->

            <div class="modal-content" id="modal-delete">
                <div class="colm12">
                    <div class="margin-auto align-center">
                        <h2>آیا از حذف دسته <span class="cat-name color-red"></span> اطمینان دارید؟</h2>
                    </div>
                </div>
                <div class="clom12 colm spacer-t40">
                    <div class="colm6 pull-right">
                        <button class="btn-web delete-ok bg-dis">بله</button>
                    </div>
                    <div class="colm6 pull-left">
                        <button class="btn-no bg-dis">خیر</button>
                    </div>
                    <div class="clearfix"></div>
                    <span class="loader-request spacer-t40"></span>
                </div>
            </div><!-- content -->
        </div><!-- modal -->
    </div><!-- overlay -->
{% endfor %}
<div id="toast">
    <div id="img">وضعیت</div>
    <div id="desc">دسته با موفقیت حذف شد</div>
</div>

<div id="toat">
    <div id="img">وضعیت</div>
    <div id="desc">دسته <span class="name color-red"></span> به تیم ها نمایش داده نمیشود</div>
</div>

<div id="toast-r">
    <div id="img">وضعیت</div>
    <div id="desc">دسته <span class="name color-red"></span> به تیم ها نمایش داده میشود</div>
</div>



<style>
    header,footer {
        display: none;
    }

</style>
{% endblock %}
{% block script %}
    <script>
        jQuery(document).ready(function($) {
            $('.cat-delete').on('click', function () {
                var elements = $('.modal-overlay, .modal');
                var catId = $(this).data('cat');
                var catName = $(this).data('name');
                var token = '{% csrf_token %}';
                elements.addClass('active');
                $('.cat-name').html(catName);
                $('.close-modal').click(function () {
                    elements.removeClass('active');
                });
                $('.btn-no').click(function () {
                    elements.removeClass('active');
                });
                $('.delete-ok').click(function() {
                    $('.bg-dis').prop('disabled',true);
                    $('.loader-request').css('display','block');
                    $.ajax({
                        // headers: { "X-CSRFToken": token },
                        url: '{% url "category:delete_cat" %}',
                        method: 'POST',
                        data: {delete_cat_id: catId, csrfmiddlewaretoken: '{{ csrf_token }}'},
                        success: function() {
                            $('#'+ catId).remove();
                            $('.loader-request').css('display','none');
                            var x = document.getElementById('toast');
                            x.className = "show";
                            elements.removeClass('active');
                            $('.bg-dis').prop('disabled',false);
                            setTimeout(function(){ x.className = x.className.replace("show", ""); }, 5000);
                        }
                    })
                });
            });
            $('.add-look').on('click', function() {
            console.log('bad');
            var t = $(this);
            var elements = $('.modal-overlay, .modal');
            var userId = $(this).data('add');
            var name = $(this).data('name');
                t.children('i').removeClass('color-blue fa-plus');
                t.children('i').addClass('color-green fa-check');
                $(this).data('name');
                $('.bg-dis').prop('disabled', true);
                jQuery('.loader-request').css('display', 'block');
                $.ajax({
                    url: '{% url "category:can_see_cat" %}',
                    method: 'POST',
                    data: {
                        add_id: userId, csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(response) {
                        jQuery('.loader-request').css('display', 'none');
                        var x = document.getElementById('toast-r');
                        x.className = "show";
                        elements.removeClass('active');
                        $('.bg-dis').prop('disabled', false);
                        setTimeout(function() {
                            x.className = x.className.replace("show", "");
                        }, 2000);
                        setTimeout(function() {
                            location.reload();
                        }, 1000);
                        t.removeClass('add-look');
                        t.addClass('del-look');

                    }
            });

        });

        // $('.del-look').on('click', function() {
        //     console.log('good');
        //     var t = $(this);
        //     var userId = $(this).data('add');
        //     var name = $(this).data('name');
        //     t.children('i').removeClass('color-green fa-check');
        //     t.children('i').addClass('color-blue fa-plus');
        //     $.ajax({
        //         url: '',
        //         method: 'POST',
        //         data: {
        //             del_id: userId
        //         },
        //         success: function(response) {
        //             var x = document.getElementById('toat');
        //             x.className = "show";
        //             setTimeout(function() {
        //                 x.className = x.className.replace("show", "");
        //             }, 2000);
        //             setTimeout(function() {
        //                 location.reload();
        //             }, 1000);
        //             t.removeClass('add-look');
        //             t.addClass('del-look');
        //         }
        //     })

        // });

        })
    </script>
{% endblock %}