message/urls.py
from django.urls import path, include
from message import views

urlpatterns = [
     path('send-message/chat/<int:user_id>/',
          views.send_message_chat, name='send_message_chat'),
     path('send-message/error/',
          views.send_message_error, name='send_message_error'),
     path('box-message/',
          views.message_box, name='message_box'),
     path('notification/', views.notification, name='notification'),
     path('show-messages/<int:allmessages_id>/', views.show_messages, name='show_messages'),
     path('support/', views.support_msg, name='support_msg'),
]

startup/urls.py
from django.urls import path, include
from startup import views
from startups.utils import export_list_csv

urlpatterns = [
     path('popups/<int:requests_id>/', views.pop_up, name='pop_up'),
     path('list-startup/', views.list_startup, name='list_startup'),
     path('list-referee/', views.list_referee, name='list_referee'),
     path('list-investor/', views.list_investor, name='list_investor'),
     path('investor-can-see/', views.investor_can_see, name='investor_can_see'),
     path('add-for-invest/', views.add_for_invest, name='add_for_invest'),
     path('list-coach/', views.list_coach, name='list_coach'),
     path('list-accelerator/', views.list_accelerator, name='list_accelerator'),
     path('delete-accelerator/', views.delete_accelerator,
          name='delete_accelerator'),
     path('edit-startup/<int:startup_id>/', views.edit_startup, name='edit_startup'),
     path('information-startup/<int:startup_id>/', views.information_startup, name='information_startup'),
     path('delete-startup/', views.delete_startup, name='delete_startup'),
     path('delete-referee/', views.remove_referee_form_startup, name='remove_referee_form_startup'),
     path('select-startup/', views.select_startup, name='select_startup'),
     path('my-startup/', views.my_startup_information, name='my_startup_information'),
     path('score-again/', views.can_score_again, name='can_score_again'),

     path('edit-accelerator/<int:shetabdahande_id>/',
          views.edit_accelerator, name='edit_accelerator'),

     path('create-accelerator/', views.create_accelerator,
          name='create_accelerator'),
     path('information/<int:startup_id>/', views.information, name='information'),
     path('reconsider/', views.reconsider, name='reconsider'),
     path('information-accelerator/<int:id>/', views.information_accelerator,
          name='information_accelerator'),
     path('manage-request/', views.manage_request, name='manage_request'),
     path('request-money/', views.request_money, name='request_money'),
     path('send-request-money/', views.send_request_money, name='send_request_money'),
     path('madrak-doc/<int:startup_id>/', views.verify_startup_documents, name='verify_startup_documents'),
     path('startup-doc/<int:startup_id>/', views.startup_assessment, name='startup_assessment'),
     path('modir-doc/<int:startup_id>/', views.verify_not_presence_referee, name='verify_not_presence_referee'),
     path('suspend/<int:startup_id>/', views.suspend_startup, name='suspend_startup'),
     path('pres-doc/<int:startup_id>/', views.verify_presence_referee, name='verify_presence_referee'),
     path('single-requestmoney/<int:requests_id>/', views.single_requestmoney, name='single_requestmoney'),
     path('export/xls/<the_model>/', export_list_csv, name='export_list_csv'),
     path('add-to-investor/<int:startup_id>/', views.add_to_investor, name='add_to_investor'),
]

startups/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from usercp import views
from .api import shetabs_json, startups_api

urlpatterns = [
     path('', views.redirect_url_to_register, name='redirect_url'),
     path('admin/', admin.site.urls),
     path('admin/doc/', include('django.contrib.admindocs.urls')),
     path('', include(('usercp.urls', 'usercp'), namespace='usercp')),
     path('', include(('startup.urls', 'startup'), namespace='startup')),
     path('', include(('theevent.urls', 'theevent'), namespace='theevent')),
     path('', include(('category.urls', 'category'), namespace='category')),
     path('', include(('usertracker.urls', 'usertracker'), namespace='usertracker')),
     path('', include(('message.urls', 'message'), namespace='message')),

     path('api/', shetabs_json, name='shetabs_json'),
     path('api/startup/', startups_api, name='shetabs_json'),
     path('logs/all', views.all_logs, name='my_logs'),
     path('logs/urls', views.url_logs, name='url_logs'),
]

handler404 = views.my_404_error
handler500 = views.my_500_error

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

theevent/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('offerto-leader/', views.offerto_leader, name='offerto_leader'),
    path('list-offer/', views.list_offer, name='list_offer'),
    path('list-meeting/', views.list_meeting, name='list_meeting'),
    path('edit-meeting/<int:theevent_id>/', views.edit_meeting_coach, name='edit_meeting_coach'),
    path('edit-offer/<int:theevent_id>/', views.edit_offer_to_leader, name='edit_offer_to_leader'),
    path('edit-event/<int:theevent_id>/', views.edit_create_event, name='edit_create_event'),
    path('wants-meet/', views.wants_to_meet, name='wants_to_meet'),
    path('list-event/', views.list_event, name='list_event'),
    path('meeting-coach/', views.meeting_coach, name='meeting_coach'),
    path('create-event/', views.create_event, name='create_event'),
    path('add-to-leader/', views.add_to_leader, name='add_to_leader'),
]

usercp/urls.py
from django.conf.urls import url
from django.urls import path, include
from usercp import views
from django.contrib.auth.views import LoginView, PasswordResetView

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('dashboard/', views.dashboard_panel, name='dashboard_panel'),
    path('mentors/', views.profile_mentor, name='profile_mentor'),
    path('sort-mentors/', views.sort_mentors, name='sort_mentors'),
    path('add-to-mentor/', views.add_to_mentor, name='add_to_mentor'),
    path('verify/', views.verify_user, name='verify'),
    path('send-sms/verify', views.send_sms_again, name='send_sms_again'),
    path('startup/', views.startup, name='startup'),
    path('team/', views.team, name='team'),
    path('upload/', views.upload, name='upload'),
    path('uploadv/', views.upload_video_action, name='upload_video'),
    path('presentation/', views.presentation, name='presentation'),
    path('upload-pdf/<int:startup_id>/', views.pgdeck, name='pgdeck_pdf'),
    path('upload-xwlt/<int:startup_id>/', views.pgdeckxwlt, name='pgdeckxwlt'),
    path('finish/', views.finish, name='finish'),
    path('profiles/<int:user_id>/', views.profiles, name='profiles'),
    path('remove-team-member/', views.remove_team_member, name='remove_team_member'),
    # path('remove-video/', views.remove_video, name='remove_video'),
    # path('remove-from-mentor/', views.remove_from_mentor,
    #      name='remove_from_mentor'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('ghost/<int:user_id>/', views.ghost_mode, name='ghost_mode'),
    path('ghost-out/', views.ghost_mode_out, name='ghost_mode_out'),
    path('list-user/', views.list_user, name='list_user'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('create-user/', views.create_user, name='create_user'),
    path('login/', views.login_view, name='login'),
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('forget-password/', views.forget_password, name='forget_password'),
    path('change-username/', views.change_username, name='change_username'),
    path('change-password/', views.change_password, name='change_password'),
    url(r'^new-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.new_password, name='new_password'),
]

message/models.py
from django.db import models
from usercp.models import User
from usertracker.models import TheStatus
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

# Create your models here.

class NotificationManager(models.Manager):
    """a custom manager model for conten_type objects

    Arguments:
        models {MODULE} -- a django built-in class to define tables
    """    
    def create_by_model(self, user, status, instance):
        """to create notification object

        Arguments:
            user {OBJECT} -- get User model object
            status {STRING} -- the status of the notification
            instance {OBJECT} -- is the object the norification is about

        Returns:
            ORM -- return inharitanced ORM(create)
        """        
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.pk
        return super().create(content_type=content_type, object_id=obj_id, status=status, user=user)

class Notification(models.Model):
    """this table contains user field to define requested user
       content_object is to define which object this notification is about

    Arguments:
        models {MODULE} -- a django built-in class to define tables

    Returns:
        STRING -- returns user and the status of the notification
    """    
    user = models.ForeignKey(User, related_name='notification', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    status = models.ForeignKey(TheStatus, related_name='notification', on_delete=models.CASCADE)
    is_readed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = NotificationManager()

    def __str__(self):
        return f"{self.user} -- {self.status}"



class SendMessage(models.Model):
    """this table contains sender receiver and receivers if there is bulk messages and content
       and is_readed field to check if message is readed or not

    Arguments:
        models {MODULE} -- a django built-in class to define tables

    Returns:
        STRING -- returns first name and last name of sender
    """    
    sender = models.ForeignKey(
        User, related_name='messagesender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(
        User, related_name='messagereceiver', blank=True, null=True, on_delete=models.SET_NULL)
    receivers = models.ManyToManyField(
        User, related_name='messagereceivers', blank=True)
    message_content = models.TextField()
    url = models.URLField(blank=True, null=True)
    is_readed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return f"{self.sender.first_name} {self.sender.last_name}"


class AllMessages(models.Model):
    """this model acts like a chat room that includes some messages
       with the title of message and the type of message

    Arguments:
        models {MODULE} -- a django built-in class to define tables
    """    
    message_title = models.CharField(max_length=120)
    send_message = models.ManyToManyField(
        SendMessage, 'allmessages', blank=True)
    THE_TYPE = (
        ('chat', 'گفتگو'),
        ('error', 'گزارش خطا'),
    )
    message_type = models.CharField(max_length=5, choices=THE_TYPE, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)


class SupportModel(models.Model):
    """this model designed for startup ownres to send errors to support staff

    Arguments:
        models {MODULE} -- a django built-in class to define tables
    """    
    user = models.ForeignKey(
        blank=True, null=True, on_delete=models.SET_NULL, related_name='support', to=User)
    phone = models.CharField(max_length=15)
    name = models.CharField(max_length=120)
    image = models.ImageField(blank=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

usercp/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, SetPasswordForm
from django.contrib.auth import authenticate
from .models import User, Role
from startup.models import UserProfile


class UserStartupRegisterForm(forms.ModelForm):
    """a custom form for admin.py
    
    Arguments:
        forms {MODULE} -- a django built-in ModelForm
    
    Raises:
        forms.ValidationError: raise an error if passowrds don't match
    
    Returns:
        OBJECT -- returns created user
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        models = User
        fields = ('phone', 'email',)

    def clean_password2(self):
        """check if the passwords match
        
        Raises:
            forms.ValidationError: raise an error if passwords are not match
        
        Returns:
            STRING -- returns password2
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        """set user passowrd before saving to database
        
        Keyword Arguments:
            commit {BOOLEAN} -- to stop commit when setting password (default: {True})
        
        Returns:
            OBJECT -- returns created user
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'phone', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]




class UserProfileForm(forms.ModelForm):
    """a form for startups owner to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        models = UserProfile
        exclude = ('user',)



class UserRegisterForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('phone',)


class UserCreateRole(forms.ModelForm):
    """a form to create karmand type user
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'email')


class LeaderForm(forms.ModelForm):
    """a form for startups owner to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = UserProfile
        fields = ('saham', 'duration_per_month')


class LeaderUserForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('phone', 'first_name', 'last_name',
                  'email', 'linkdin', 'grade', 'skill')



class KarmandForm(forms.ModelForm):
    """a form to create karmand type user
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'phone', 'email', 'linkdin', 'multi', 'avatar', 'can_see_startups')


class ProfileAdminForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('email', 'linkdin', 'skill', 'grade')


class ProfileRoleForm(forms.ModelForm):
    """a form for user to fill additional information
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    class Meta:
        model = User
        fields = ('email', 'linkdin', 'twitter', 'site',
                  'city', 'instagram', 'bio', 'skill', 'grade')


class PasswordChangeForm(SetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = {
        **SetPasswordForm.error_messages,
    }

    field_order = ['new_password1', 'new_password2']





class LoginForm(forms.Form):
    """a custom form for login
    
    Arguments:
        forms {MODULE} -- a django built-in Model Form
    """
    username = forms.CharField(max_length=120)
    password = forms.CharField(
        max_length=120, widget=forms.PasswordInput)

usercp/templates/usercp/panel/dashboard/dashboard-admin.html
<style>
	.hide-tab{
		display: none;
	}
</style>

<div class="pad-t40">
    <div class="colm7 colm pull-right pad-t40 pad-15 pad-5-mob spacer-t25-mob">
        <div class="body-form relative wow fadeInUpBig" data-wow-duration="1s">
            <div class="pad-b10">
                <div class="body-form-top absolute flex-center">
                    <i class="fa fa-chart-bar vertical font-s30 color-white"></i>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18">ثبت نام ماهانه استارتاپ ها</h3>
                </div>
                <div class="pull-left pad-10">
                    <span class="pad-10 pointer lastyear" title="سال قبل"><i class="fa fa-arrow-left"></i></span>
                </div>
                <div class="pull-left pad-10">
                    <span class="pad-10 pointer thisyear" title="سال جاری">{{th_year}}</span>
                </div>
                <div class="pull-left pad-10">
                    <span class="pad-10 pointer nextyear" title="سال بعد"><i class="fa fa-arrow-right"></i></span>
                </div>
            </div>
            <div id="load-request">
                <div id="load-request-content" class="frm-row pad-t40">
                    <div id="chartdivregister" data-year="{{th_year}}"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="colm5 colm pull-right pad-t40 pad-15 pad-5-mob spacer-t25-mob">
        <div class="body-form relative wow fadeInUpBig" data-wow-duration="1s">
            <div class="pad-b10">
                <div class="body-form-top absolute flex-center">
                    <i class="fa fa-chart-pie vertical font-s30 color-white"></i>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18">تفکیک کاربران سامانه</h3>
                </div>
            </div>
            <div class="frm-row pad-t40">
                <div id="chartdivtafkik"></div>
            </div>
        </div>
    </div>
	<div class="frm-row">
		    <div class="colm12 colm">
            <div class="clearfix"></div>
        </div>
	</div>
	

	<div class="clearfix"></div>
</div>
<style>
	rect.highcharts-background{
		fill:transparent
	}
	g.highcharts-exporting-group {
    display: none;
}
text.highcharts-credits {
    display: none;
}
.activee {
     background: #eeeeee;
     color: #222;
}
.cursor-step{
	cursor: context-menu;
}
</style>

usercp/templates/usercp/panel/dashboard/dashboard-coach.html
<style>
	.hide-tab{
		display: none;
	}
</style>
<div class="pad-t40">

	
</div>
<style>
	rect.highcharts-background{
		fill:transparent
	}
	g.highcharts-exporting-group {
    display: none;
}
text.highcharts-credits {
    display: none;
}
</style>

usercp/templates/usercp/panel/dashboard/dashboard-financial.html
{% load jalali_tags %}
<style>
	.hide-tab{
		display: none;
	}
</style>
<div class="pad-t40">
	<div class="frm-row pad-t40 pad-15 pad-5-mob spacer-t25-mob">
		<div class="body-form relative wow fadeInUpBig" data-wow-duration="1s">
			<div class="pad-b10">
     			<div class="bg-chart2 body-form-top absolute flex-center">
					<i class="fa fa-file-invoice-dollar vertical font-s30 color-white"></i>
				</div>
				<div class="absolute title-panel">
					<h3 class="font-w300 font-s18">10 درخواست آخر</h3>
				</div>
				<div class="frm-row pad-t25-mob pad-t30-tab">
					<div class="colm4 colm12-tab colm pull-left pull-none relative pad-20">

				    </div>
				</div>
			</div>
			<div class="frm-row pad-t40 pad-b10-mob pad-b10-tab pad-b20 overflow-scroll">
				<div class="pad-table">
                <table class="table color6">
                    <thead>
                    <tr>
						<th class="center">نام تیم</th>
                        <th class="center">عنوان</th>
                        <th class="center">مبلغ</th>
                        <th class="center">تاریخ درخواست</th>
                        <th class="center">وضعیت</th>
                        <th class="center">جزئیات</th>
                    </tr>
                    </thead>
                    <tbody>
{% for req in the_requests %}
                            <tr class="{{req.id }}">
								<td class="center">{{ req.startup.title }}</td>
                                <td class="center">{{ req.request_title }}</td>
                                <td class="center">{{ req.request_money }}</td>
                                <td class="center">{{ req.created_date|to_jalali:'%y/%m/%d' }}</td>
                                <td class="center">{{ req.get_status_display }}</td>
                                <td class="center">
                                    <a class="color-silver" title="نمایش" href="{% url 'startup:single_requestmoney' req.pk %}">
                                    <span>
	                                	<i class="align-center font-s20 fa fa-address-card"></i>
									</span>
                                    </a>
                                </td>
                            </tr>
{% endfor %}
                    </tbody>
                </table>
				</div>
			</div>
		</div>
	</div>
    <div class="clearfix"></div>
</div>
<style>
	rect.highcharts-background{
		fill:transparent
	}
	g.highcharts-exporting-group {
    display: none;
}
text.highcharts-credits {
    display: none;
}
.activee {
     background: #eeeeee;
     color: #222;
}
.cursor-step{
	cursor: context-menu;
}
</style>

usercp/templates/usercp/panel/dashboard/dashboard-leader.html
{% load sunny %}
<div class="pad-t40">
    <div class="frm-row pad-t40 spacer-b25-mob pad-5-mob pad-15">
        <div class="body-form relative wow fadeInUpBig" data-wow-duration="1s">
            <div class="pad-b10">
                <div class="bg-chart1 body-form-top absolute flex-center">
                    <i class="fa fa-pause vertical font-s30 color-white"></i>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18 font-s12-mob">لیست استارت آپ های قابل راهبری</h3>
                </div>
                <!-- <form method="get" action="" class="pad-20 spacer-t20">
					<div class="spacer-t20">
					  <div class="spacer-t10 pad-t40 relative colm3 colm pull-right pad-5 pad-b20">
						<label for="name-startup-leader" class="gui-label">نام استارتاپ:</label>
						<label class="relative">
						  <span class="icon-gui flex-center"><i class=" fa fa-rocket vertical"></i></span>
						  <input type="search" value="" name="name_startup_leader" id="name-startup-leader" class="gui-input">
						</label>
					  </div>
					  <div class="pull-left align-center pad-t20 pad-b20">
						<button name="submit_search" type="submit"
								class="btn-search btn-panel pad-6 spacer-t54 color-white iransans spacer-t10 pointer">جستجو
						</button>
					  </div>
					  <div class="clearfix"></div>
					</div>
				  </form> -->
                <div class="frm-row  pad-t25-mob pad-t30-tab">
                    <div class="colm4 colm12-tab colm pull-left pull-none relative pad-20">
                        <span class="bar"></span>
                    </div>
                </div>
            </div>
            <div class="frm-row pad-t40">
                <div class="overflow-scroll pad-b40">
                    <table class="table color6 retable">
                        <thead>
                        <tr>
                            <th class="center">نام استارت آپ</th>
                            <th class="center">حوزه فعالیت</th>
                            <th class="center">میزان سرمایه درخواستی</th>
                            <th class="center">پیچ دک</th>
                            <th class="center">تمایل به راهبری</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for th_leader in leader_start %}
                            {% for c_event in th_leader.c_event.all %}
                            {% if c_event.content_object.pk == request.user.pk %}
                            {% for th_startup in c_event.theevent_leadermodel.all %}
                            {% ifchanged %}
                        <tr>
                            <td class="center">{{th_startup.startup.title}}</td>
                            <td class="center">{% for cat in th_startup.startup.category.all%}{% if not forloop.last %} و {% endif %}{{cat.title}}{% endfor %}</td>
                            <td class="center">{{th_startup.startup.require_money}}</td>
                            <td class="center">
                                {% if th_startup.startup.pk %}
                                <a class="color-silver pointer" title="نمایش اطلاعات پیچ دک" href="{% url 'startup:information_startup' th_startup.startup.pk %}">
                                    <i class="align-center font-s20 fa fa-rocket"></i>
                                </a>
                                {% endif %}
                            </td>
                            <td class="center">

                                <span class="color-silver add-leader pointer" title="نمایش" data-url="{% url 'theevent:add_to_leader' %}" data-stat-id="{{th_startup.startup.pk}}" data-name="{{ th_startup.startup.title }}" data-startup-id="{{th_startup.pk}}" data-status="{{ th_startup.status }}" data-title="{{th_startup.startup.about_start}}">
                                    <i class="font-s25 fa {% if th_startup.status == 1 %}fa-check color-green {% elif th_startup.status == 0 %}  fa-plus color-blue{% endif %}"></i>
                                </span>
                            </td>
                        </tr>
                        {% endifchanged %}
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- modal -->
<div class="modal-overlay1">
    <div class="modal1">

        <a class="close-modal">
            <svg viewBox="0 0 20 20">
                <path fill="#000000" d="M15.898,4.045c-0.271-0.272-0.713-0.272-0.986,0l-4.71,4.711L5.493,4.045c-0.272-0.272-0.714-0.272-0.986,0s-0.272,0.714,0,0.986l4.709,4.711l-4.71,4.711c-0.272,0.271-0.272,0.713,0,0.986c0.136,0.136,0.314,0.203,0.492,0.203c0.179,0,0.357-0.067,0.493-0.203l4.711-4.711l4.71,4.711c0.137,0.136,0.314,0.203,0.494,0.203c0.178,0,0.355-0.067,0.492-0.203c0.273-0.273,0.273-0.715,0-0.986l-4.711-4.711l4.711-4.711C16.172,4.759,16.172,4.317,15.898,4.045z"></path>
            </svg>
        </a><!-- close modal -->

        <div class="modal-content" id="modal-delete">
            <div class="colm12">
                <div class="margin-auto align-center">
                    <h2><span class="title"> </span><span class="name color-red"> </span></h2>
                </div>
            </div>
            <div class="clom12 colm spacer-t40">
                <div class="flex-center">
                    <button type="submit" name="interest" value="" class="btn-interest bg-dis spacer-t40 colm12 colm"></button>
                </div>
                <div class="clearfix"></div>
                <span class="loader-request spacer-t40"></span>
            </div>
        </div><!-- content -->
    </div><!-- modal -->
</div><!-- overlay -->
<div id="toast-leader">
    <div id="img">وضعیت</div>
    <div id="desc">شما راهبر استارتاپ  <span class="name color-red"></span> شدید</div>
</div>
<div id="toast-not-leader">
    <div id="img-not">وضعیت</div>
    <div id="desc-not">شما از راهبری <span class="name color-red"></span> انصراف دادید</div>
</div>
<style>

    rect.highcharts-background{
        fill:transparent
    }
    g.highcharts-exporting-group {
        display: none;
    }
    text.highcharts-credits {
        display: none;
    }
</style>