startups/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from usercp import views
from .api import shetabs_json, startups_api

urlpatterns = [
     path('', views.redirect_url_to_register, name='redirect_url'),
     path('admin/', admin.site.urls),
     path('admin/doc/', include('django.contrib.admindocs.urls')),
     path('', include(('usercp.urls', 'usercp'), namespace='usercp')),
     path('', include(('startup.urls', 'startup'), namespace='startup')),
     path('', include(('theevent.urls', 'theevent'), namespace='theevent')),
     path('', include(('category.urls', 'category'), namespace='category')),
     path('', include(('usertracker.urls', 'usertracker'), namespace='usertracker')),
     path('', include(('message.urls', 'message'), namespace='message')),

     path('api/', shetabs_json, name='shetabs_json'),
     path('api/startup/', startups_api, name='shetabs_json'),
     path('logs/all', views.all_logs, name='my_logs'),
     path('logs/urls', views.url_logs, name='url_logs'),
]

handler404 = views.my_404_error
handler500 = views.my_500_error

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

theevent/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('offerto-leader/', views.offerto_leader, name='offerto_leader'),
    path('list-offer/', views.list_offer, name='list_offer'),
    path('list-meeting/', views.list_meeting, name='list_meeting'),
    path('edit-meeting/<int:theevent_id>/', views.edit_meeting_coach, name='edit_meeting_coach'),
    path('edit-offer/<int:theevent_id>/', views.edit_offer_to_leader, name='edit_offer_to_leader'),
    path('edit-event/<int:theevent_id>/', views.edit_create_event, name='edit_create_event'),
    path('wants-meet/', views.wants_to_meet, name='wants_to_meet'),
    path('list-event/', views.list_event, name='list_event'),
    path('meeting-coach/', views.meeting_coach, name='meeting_coach'),
    path('create-event/', views.create_event, name='create_event'),
    path('add-to-leader/', views.add_to_leader, name='add_to_leader'),
]

usercp/urls.py
from django.conf.urls import url
from django.urls import path, include
from usercp import views
from django.contrib.auth.views import LoginView, PasswordResetView

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('dashboard/', views.dashboard_panel, name='dashboard_panel'),
    path('mentors/', views.profile_mentor, name='profile_mentor'),
    path('sort-mentors/', views.sort_mentors, name='sort_mentors'),
    path('add-to-mentor/', views.add_to_mentor, name='add_to_mentor'),
    path('verify/', views.verify_user, name='verify'),
    path('send-sms/verify', views.send_sms_again, name='send_sms_again'),
    path('startup/', views.startup, name='startup'),
    path('team/', views.team, name='team'),
    path('upload/', views.upload, name='upload'),
    path('uploadv/', views.upload_video_action, name='upload_video'),
    path('presentation/', views.presentation, name='presentation'),
    path('upload-pdf/<int:startup_id>/', views.pgdeck, name='pgdeck_pdf'),
    path('upload-xwlt/<int:startup_id>/', views.pgdeckxwlt, name='pgdeckxwlt'),
    path('finish/', views.finish, name='finish'),
    path('profiles/<int:user_id>/', views.profiles, name='profiles'),
    path('remove-team-member/', views.remove_team_member, name='remove_team_member'),
    # path('remove-video/', views.remove_video, name='remove_video'),
    # path('remove-from-mentor/', views.remove_from_mentor,
    #      name='remove_from_mentor'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('ghost/<int:user_id>/', views.ghost_mode, name='ghost_mode'),
    path('ghost-out/', views.ghost_mode_out, name='ghost_mode_out'),
    path('list-user/', views.list_user, name='list_user'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('create-user/', views.create_user, name='create_user'),
    path('login/', views.login_view, name='login'),
    path('verify-phone/', views.verify_phone, name='verify_phone'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('forget-password/', views.forget_password, name='forget_password'),
    path('change-username/', views.change_username, name='change_username'),
    path('change-password/', views.change_password, name='change_password'),
    url(r'^new-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.new_password, name='new_password'),
]

theevent/models.py
from django.db import models
from usercp.models import User
from startup.models import StartUp
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

# Create your models here.


class CreateEventManager(models.Manager):
    """A custom model manager for CreateEvent for filter and create based on model class instance

    Arguments:
        models {MODULE} -- a django built-in module to create custom ORM
    """
    def create_by_model(self, instance):
        """create a record based on model instances

        Arguments:
            instance {OBJECT} -- an object that will be used as content_object

        Returns:
            QUERYSET -- returns queryset of created object
        """        
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.pk
        queryset = super().create(content_type=content_type, object_id=obj_id)
        return queryset

    def filter_by_model(self, instance):
        """filter the records or objects based on model class instance

        Arguments:
            instance {OBJECT} -- an object that will be used as content_object

        Returns:
            QUERYSET -- returns queryset of filtered objects
        """        
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        return super().filter(content_type=content_type, object_id=obj_id)




class CreateEvent(models.Model):
    """this model is actully define the user that we wants offer/assign some values such as startups or busy or free status

    Arguments:
        models {MODULE} -- a django built-in class to define tables
    """    
    content_type = models.ForeignKey(
        ContentType, blank=True, null=True, on_delete=models.SET_NULL)
    object_id = models.PositiveIntegerField(default=0)
    content_object = GenericForeignKey('content_type', 'object_id')
    created_date = models.DateTimeField(
        auto_now_add=True, blank=True, null=True)
    objects = CreateEventManager()

    def __str__(self):
        try:
            return f'{self.content_object.user.first_name} {self.content_object.user.last_name}'
        except:
            return str(self.id)

class EventAbstract(models.Model):
    """an abstract class to create only one table with nearly same fields for models like:
       - StartupsEvent
       - CoachEvent
       - LeaderModel

    Arguments:
        models {MODULE} -- a django built-in class to define tables
    """    
    event = models.ForeignKey(
        CreateEvent, related_name="%(app_label)s_%(class)s", on_delete=models.CASCADE)
    startup = models.ForeignKey(
        StartUp, related_name="%(app_label)s_%(class)s", blank=True, null=True, on_delete=models.SET_NULL)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class TheEvent(models.Model):
    """the table that will be use in every event that store the id of the event and the type of the event

    Arguments:
        models {MODULE} -- a django built-in class to define tables
    """    
    id = models.IntegerField(blank=True, null=True)
    the_id = models.AutoField(primary_key=True, unique=True)
    owner = models.ForeignKey(
        User, related_name='theevent', on_delete=models.CASCADE)
    c_event = models.ManyToManyField(
        CreateEvent, related_name='theevent', blank=True)
    THE_TYPE = (
        ('investor', "سرمایه گذار"),
        ('coach', "مربی"),
        ('leader', "راهبر"),
    )
    th_type = models.CharField(
        max_length=20, default='investor', choices=THE_TYPE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.th_type} -- {self.c_event.all()}"

class StartupsEvent(EventAbstract):
    """an inharitansed model to assign startups to investors (create_event)

    Arguments:
        EventAbstract {ABSTRACT MODEL} -- this class is inharitanced from EventAbstract for less table craetion
    """    
    schedule = models.OneToOneField('StartupTime', related_name='startupsevent', blank=True, null=True, on_delete=models.CASCADE)
    class Meta:
        ordering = ('-created_date',)


class CoachEvent(EventAbstract):
    THE_TYPE = (
        (1, 'ازاد'),
        (2, 'پر'),
    )
    th_time = models.SmallIntegerField(choices=THE_TYPE)
    schedule = models.OneToOneField('StartupTime', related_name='coachevent', blank=True, null=True, on_delete=models.CASCADE)


class WantsMeet(models.Model):
    the_event = models.OneToOneField(
        TheEvent, related_name='wantsmeet', on_delete=models.CASCADE)
    startup = models.ForeignKey(
        StartUp, related_name='wantsmeet', blank=True, null=True, on_delete=models.SET_NULL)
    c_event = models.ForeignKey(
        CreateEvent, related_name='wantsmeet', blank=True, null=True, on_delete=models.SET_NULL)
    event_counter = models.SmallIntegerField(default=1)

    created_date = models.DateTimeField(auto_now_add=True)


class StartupTime(models.Model):
    the_event = models.ForeignKey(
        TheEvent, related_name='startuptime', blank=True, null=True, on_delete=models.SET_NULL)
    the_date = models.DateTimeField(blank=True, null=True)
    to_date = models.DateTimeField(blank=True, null=True)
    from_time = models.TimeField(blank=True, null=True)
    to_time = models.TimeField(blank=True, null=True)
    created_date = models.DateTimeField(
        auto_now_add=True, blank=True, null=True)


class LeaderModel(EventAbstract):
    THE_STATUS = (
        (1, 'iwant'),
        (0, 'idontwant'),
    )
    status = models.IntegerField(choices=THE_STATUS, default=0)

    def __str__(self):
        return f"{self.startup} {self.status}"

theevent/templates/theevent/list-event.html
{% extends 'base/base-panel.html' %}
{% load static %}
{% load sunny %}
{% load jalali_tags %}
{% block title %}لیست ایونت ها{% endblock %}
{% block body %}
    <style>
        header,
        footer {
            display: none;
        }

        .hide-tab {
            display: none;
        }
    </style>
                                {% for event in events %}
    <div class="pad-t20">
            <div class="body-form  relative spacer-t30">
                <div class="bg-chart2 body-form-top absolute flex-center">
                    <i class="fa fa-handshake vertical font-s30 color-white"></i>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18  hide-mob">
                        <span class="color-dashboard font-s13">ایجاد کننده رویداد : {{ event.owner.first_name }} {{ event.owner.last_name }}</span>
                    </h3>
                </div>
                <div class="pull-left pad-10">
					{# <a href="{% url 'theevent:edit_create_event' event.pk %}" class="btn-excel color-white font-s11 iransans pad-5"><i class="fa fa-edit pad-l5 vertical"></i>ویراش رویداد</a>   #}
				</div>
                <span class="color-dashboard font-s12 pull-left pad-10  hide-mob">تاریخ ایجاد : {{ event.created_date|to_jalali:'%Y/%m/%d'}}</span>
                <div class="clearfix"></div>
                <div class="frm-row pad-t40">
                    <div class="overflow-scroll pad-b40">
                        <table class="table color6 retable">
                            <thead>

                                <tr>
                                    <th>سرمایه گذار</th>
                                    {% time_event event as startups %}
                                    {% for startup in startups %}

                                    <th class="btn-intro">
                                        <div class="flex-center">
                                            <input type="hidden" class="time{{ forloop.counter }}"  name="time{{ forloop.counter }}" value="{{ startup.the_date }}{{ startup.from_time }}{{ startup.to_time }}">
                                            <time class="digit display-block font-w300 font-s13 color-blue day">{{ startup.from_time|time:"H:i" }} تا {{ startup.to_time|time:"H:i" }}</time>                                  
                                            <p class="font-s14 color-startup  ">{% if startup.the_date %}{{ startup.the_date|to_jalali:'%Y/%m/%d' }}{% else %}تاریخ ثبت نشده{% endif %}</p>
                                            
                                        </div>
                                    </th>
                                    {% endfor %}
                                    {% if startups.count == 4 %}
                                    {% else %}
                                    {% list_counter2 startups.count as c %}
                                    {% for item in 'x'|rjust:c %}
                                    <th class="btn-intro">
                                        <div class="flex-center">

                                            <p class="font-s14 color-startup  ">تاریخ ثبت نشده</p>
                                            
                                        </div>
                                    </th>
                                {% endfor %}
                                {% endif %}

                            </thead>

                            <tbody>
                                
                                {% for x in event.c_event.all %}
                                <tr id="{{ x.pk }}" class="">
                                    <td>
                                        <div class="relative pull-right pad-5 pad-b20">
                                            <label for="" class="gui-label">سرمایه گذار: </label>
                                            <label class="relative">
                                                <span class="icon-gui flex-center"><i class=" fa fa-chalkboard-teacher vertical"></i></span>
                                                <input type="text"  class="w165-mob search_companion referee-name gui-input iransans  choosen-name" value="{{x.content_object.user.first_name }} {{x.content_object.user.last_name }} "  disabled>

                                                <div id="companion-result"></div>
                                            </label>
                                        </div>
                                    </td>
                                    {% startups_c_event x as startups %}
                                   
                                   {% for startup in startups %}
                                    <td>
 
                                        <div class="relative pull-right pad-5 pad-b20">
                                            <label for="roles-search" class="gui-label">استارتاپ:</label>
                                            <label class="relative pad-b20">
                                                <span class="icon-gui flex-center"><i class=" fa fa-user vertical"></i></span>
                                                <input class="w165-mob input-mentor gui-input save-s s1 iransans" value="{% if startup %}{{ startup.startup.title }}{% else %}استارتاپ ثبت نشده{% endif %}" disabled>
                                                </i>
                                            </label>
                                        </div>
                                    </td>
                                    {% endfor %}
                                    {% if startups.count == 4 %}
                                    {% else %}
                                    {% list_counter2 startups.count as c %}
                                    {% for item in 'x'|rjust:c %}
                                    <td>
 
                                        <div class="relative pull-right pad-5 pad-b20">
                                            <label for="roles-search" class="gui-label">استارتاپ:</label>
                                            <label class="relative pad-b20">
                                                <span class="icon-gui flex-center"><i class=" fa fa-user vertical"></i></span>
                                                <input class="w165-mob input-mentor gui-input save-s s1 iransans" value="استارتاپ ثبت نشده" disabled>
                                                </i>
                                            </label>
                                        </div>
                                    </td>
                                {% endfor %}
                                {% endif %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
        </div>
    {% empty %}
        {% endfor %}
{% endblock %}

theevent/templates/theevent/list-meeting.html
{% extends 'base/base-panel.html' %} {% load static %} {% load sunny %} {% load jalali_tags %} {% block title %}لیست ملاقات ها{% endblock %} {% block body %}
<style>
	.hide-tab {
		display: none;
	}

	header,
	footer {
		display: none;
	}

	.gui-select {
		padding: 5px 20px;
	}

	.searchresult {
		left: unset;
		width: 265;
	}

	.accept-time {
		background: #759872;
		border: none;
		color: #f0f8f8;
		font-size: 11px;
	}

	.failed-time {
		background: #9c3131;
		color: aliceblue;
		border: none;
		font-size: 11px;
	}

	.none-time {
		background: #0000000d;
		border: none;
		padding: 15px;
	}
</style>
<div class="colm12 colm  margin-auto">
	<div class="spacer-t25">
		<div class="pad-t20">
			{% for meet in meetings %}
			<div class="body-form relative spacer-t30">
				<div class="bg-chart2 body-form-top absolute flex-center">
					<i class="fa fa-handshake vertical font-s30 color-white"></i>
				</div>
				<div class="absolute title-panel">
					<h3 class="font-w300 font-s18">
						<span class="color-dashboard font-s13  hide-mob">ایجاد کننده: {{ meet.owner.first_name }} {{ meet.owner.last_name }}</span>
					</h3>
				</div>
				<div class="pull-left pad-10">
					<a href="{% url 'theevent:edit_meeting_coach' meet.pk %}" class="btn-excel color-white font-s11 iransans pad-5"><i class="fa fa-edit pad-l5 vertical"></i>ویراش جلسه</a>   
				  </div>
				<span class="color-dashboard font-s12 pull-left pad-10 hide-mob">تاریخ پایان جلسه : {{ meet.startuptime.first.to_date|to_jalali:'%y/%m/%d'}}</span>
				<span class="color-dashboard font-s12 pull-left pad-10 hide-mob">تاریخ شروع جلسه : {{ meet.startuptime.first.the_date|to_jalali:'%y/%m/%d'}}</span>
				<div class="clearfix"></div>
				<div class="frm-row pad-t40 pad-b10">
					<div class="overflow-scroll pad-b20">
						<table class="table color6 retable">
							<thead>

								<tr>
									<th>مربی</th>
									{% ifchanged %}
									{% for th_time in meet.startuptime.all %}
									<th class="btn-intro">
										<div class="flex-center">
											<p class="font-s11 color-startup  ">
												{{th_time.from_time|time:"H:i"}} تا 
												{{th_time.to_time|time:"H:i"}}
											</p>
										</div>
									</th>
									{% endfor %}
									{% if  meet.startuptime.count == 8 %}
									{% else %}
									{% list_counter  meet.startuptime.count as c %}
									{% for item in 'x'|rjust:c %}
									<th class="btn-intro">
										<div class="flex-center">
											<p class="font-s11 color-startup  ">تاریخ ثبت نشده
											</p>
										</div>
									</th>
								{% endfor %}
								{% endif %}
									{% endifchanged %}

								</tr>

							</thead>

							<tbody>
								{% for coach in meet.c_event.all %}
								<tr>
									<td class="colm4">
										<div class="colm12 relative pull-right pad-5 pad-b20">
											<div class="relative">
												<span class="icon-gui flex-center pad-t15"><i
														class=" fa fa-chalkboard-teacher vertical"></i></span>
												<div class="w165-mob search_companion referee-name gui-input iransans">
													{{ coach.content_object.first_name }} {{ coach.content_object.last_name }}
													</div>
											</div>
										</div>
									</td>
									{% for th_type in coach.theevent_coachevent.all %}
									<td class="colm1">
										<div class="colm12 align-center relative pull-right pad-5 pad-b20">
											<div class="relative pad-b20 pad-t5-mob">
												<div
													class="w100-mob  input-mentor {% if th_type.th_time == 1 %} accept-time {% else %} failed-time {% endif %} gui-select iransans ">
													{% if th_type.startup %}{{ th_type.startup.title}}{% else %}{{th_type.get_th_time_display}}{% endif %}
													</div>
												</i>
											</div>
										</div>
									</td>
									{% endfor %}
									{% if coach.theevent_coachevent.count == 8 %}
									{% else %}
									{% list_counter coach.theevent_coachevent.count as c %}
									{% for item in 'x'|rjust:c %}
									<td class="colm1">
										<div class="colm12 align-center relative pull-right pad-5 pad-b20">
											<div class="relative pad-b20 pad-t5-mob">
												<div
													class="w100-mob input-mentor gui-select iransans none-time ">
													</div>
												</i>
											</div>
										</div>
									</td>
								{% endfor %}
								{% endif %}
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

theevent/templates/theevent/list-offer.html
{% extends 'base/base-panel.html' %}
{% load static %}
{% load sunny %}
{% load jalali_tags %}
{% block title %}لیست ملاقات های راهبران{% endblock %}
{% block body %}
    <style>
        header,
        footer {
            display: none;
        }

        .hide-tab {
            display: none;
        }
    </style>

    <div class="pad-t20">
       
        {% for offer in offers %}
            <div class="body-form relative spacer-t30">
                <div class="bg-chart2 body-form-top absolute flex-center">
                    <i class="fa fa-handshake vertical font-s30 color-white"></i>
                </div>
                <div class="absolute title-panel">
                    <h3 class="font-w300 font-s18 hide-mob">               
                        <span class="color-dashboard font-s13">ایجاد کننده: {{ offer.owner.first_name }} {{ offer.owner.last_name }}</span>
                    </h3>
                </div>
                <div class="pull-left pad-10">
					<a href="{% url 'theevent:edit_offer_to_leader' offer.pk %}" class="btn-excel color-white font-s11 iransans pad-5"><i class="fa fa-edit pad-l5 vertical"></i>ویراش اختصاص راهبر</a>   
				  </div>
                <span class="color-dashboard font-s12 pull-left pad-10 hide-mob">تاریخ ایجاد : {{ offer.created_date|to_jalali:'%Y/%m/%d' }}</span>
                <div class="clearfix"></div>
                <div class="frm-row pad-t40">
                    <div class="overflow-scroll pad-b20 pad-t20">

                        {% for leader in offer.c_event.all %}
                                <div id="{{ leader.pk }}" class="colm12 colm border-b-panel spacer-b10">
                                    <div class="colm2 colm pull-right">
                                        <div class="relative pull-right pad-5 pad-b20">
                                            <span for="" class="font-s13 pad-l15">راهبر: </span>
                                            <span for="" class="font-s12 color-orange">{{ leader.content_object.first_name }} {{ leader.content_object.last_name }}</span>
                                        </div>
                                    </div>
                                  
                                        <div class="colm pull-right">
                                            <span>
                                                <div class="relative pull-right pad-5 pad-b20">
                                                    <span for="" class="font-s13">استارتاپ های پیشنهادی:{% for start_up in leader.theevent_leadermodel.all %} {% if not forloop.first %} ، {% endif %}{{ start_up.startup.title }} {% endfor %}</span>
                                                </div>
                                            </span>    
                                        </div>

                                        <div class="colm2 colm align-center pad-5 pull-right">
                                        <span>
                                            <a href="" title="نمایش" class="color-orange font-s12"></a>
                                        </span>
                                        </div>   
                                        <div class="clearfix"></div>
                                    </div>                          
{% endfor %}

                    </div>
                </div>
            </div>
            {% endfor %}

    </div>
    {% endblock %}